[phases.setup]
nixPkgs = ["python313", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate --noinput && gunicorn ai_blog_app.wsgi --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --log-file -"
